# Generated by Django 5.1.1 on 2024-10-09 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('desenvolvedor', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plataforma', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('idioma', models.TextField()),
                ('genero', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('background', models.ImageField(default='jogos/static/backgrounds', upload_to='')),
                ('data_adicionado', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
